# This will run Lighthouse on a URL, then upload the results to a private LHCI server.
name: LHCI-upload-to-private-server
on: push
jobs:
  populate-ci-server-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Lighthouse on a URL and upload data to a private LHCI server.
        uses: ./
        with:
          urls: |
            https://treo.sh/
          serverBaseUrl: ${{ secrets.LHCI_SERVER_BASE_URL }}
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}
