# Interpolate URLs with env variables.
name: LHCI-urls-interpolation
on: push
jobs:
  multiple-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Lighthouse on multiple URLs and interpolate env variables.
        uses: ./
        env:
          URL_DOMAIN: 'treo.sh'
        with:
          urls: |
            https://$URL_DOMAIN/
            https://$URL_DOMAIN/demo
